### PR TITLE
WIP: added banded LU factorisation and solution of banded linear systems

### LINKED ISSUE #3: solution of banded linear systems
Hi,
 
I almost got close to reinventing the wheel, but then had a look on METADATA and found this very interesting package.

In my work, I need to solve a banded system of equation. If you do not mind, I would like to contribute this functionality and open a WIP PR, so that you can track the progress and comment.

Thanks,

Davide

### PR DESCRIPTION
**Pull request by gasagna**
OK, as promised here is a basic interface that serves most of the purposes. ~~Currently, it is not as flexible as the factorisation interface in base julia, (e.g. `A` and  `b` must have same types), but we can improve upon this as needed.~~ 

Fixes #3.

### CODE REVIEW

**Comment by gasagna** [comment]
There is something strange in the julia profiler I do not understand. I am profiling the current factorisation code in this branch against a `fast` method that does not make any data copy. Here is the script;

````julia
using BandedMatrices

blas_set_num_threads(1)
import Base.LAPACK: gbtrf!

function fast(data, m, l, u)
    gbtrf!(l, u, m, data)
end

# sizes
N = 100
M = 1000

# data
D     = brand(N*M, N, N)
Dfast = randn(2N+N+1, N*M)

# banded lu factorisation with copy
lufact(D)
@time lufact(D)

# banded lu factorisation no copy
fast(Dfast, N*M, N, N)
@time fast(Dfast, N*M, N, N)

# profile
Profile.init(delay=2e-5)

@profile lufact(D)
Profile.print()

println()
println()

Profile.clear()
@profile fast(Dfast, N*M, N, N)
Profile.print()
````

On my mac this gives

````
  2.463709 seconds (168 allocations: 230.037 MB, 0.88% gc time)
  2.127892 seconds (11 allocations: 391.000 KB)
4134 ....5/lib/julia/sys.dylib; _start; (unknown line)
 4134 ....5/lib/julia/sys.dylib; process_options; (unknown line)
  4134 ...5/lib/julia/sys.dylib; include_from_node1; (unknown line)
   4134 ...5/lib/julia/sys.dylib; include; (unknown line)
    4134 profile.jl; anonymous; line: 16
     4118 ...ices.jl/src/blas.jl; lufact; line: 244
      3464 abstractarray.jl; setindex!; line: 592
       3    cartesian.jl; _unsafe_batchsetindex!; line: 31
       163  cartesian.jl; _unsafe_batchsetindex!; line: 34
       2850 multidimensional.jl; _unsafe_batchsetindex!; line: 328
       448  multidimensional.jl; _unsafe_batchsetindex!; line: 329
     16   ...ices.jl/src/blas.jl; lufact; line: 245
      16 linalg/lapack.jl; gbtrf!; line: 75


14 ...4.5/lib/julia/sys.dylib; _start; (unknown line)
 14 ...4.5/lib/julia/sys.dylib; process_options; (unknown line)
  14 ....5/lib/julia/sys.dylib; include_from_node1; (unknown line)
   14 ....5/lib/julia/sys.dylib; include; (unknown line)
    13 profile.jl; anonymous; line: 16
     13 linalg/lapack.jl; gbtrf!; line: 75
````

The fact is that the copy/no-copy methods take roughly the same time, with the no-copy method being slightly faster and saving a few allocations.

However, the profiling results do not make sense. It seems that a *lot* of time for `lufact(D)` is spent at line 244, where the copy is performed and only a little where the factorisation is actually done, at line 245. Interestingly, the number of samples collected for the factorisation in the `fast` version, 14, is similar to that for actual `lufact(D)` call. 

Initially I thought the data transfer was a true bottleneck, but it turns out the timings are quite similar. 

Any thoughts?

**Comment by dlfivefifty** [comment]
In my experience, the numbers in Profile are not all equal…I’m not sure what they represent.

**Comment by gasagna** [comment]
I have played with this a bit and the basic functionality seems to be OK. Could you review it? 
Thanks

**Comment by dlfivefifty** [comment]
It looks great to me, can I merge it?

**Comment by gasagna** [comment]
I have noticed a couple of bugs in how `\` behaves. Let me fix that.

**Comment by dlfivefifty** [comment]
Ok, thanks a lot for doing this!

**Comment by gasagna** [comment]
You are welcome! It is now ready for merge 🎉

**Comment by dlfivefifty** [comment]
Great!  Maybe I'll tag a new version sooner rather than later

**Pull request merged**
