### PR TITLE
RFC: Implemented `setindex`, fixes #5

### LINKED ISSUE #5: `setindex` issue
Consider this

```julia
julia> a = bones(5, 5, 1, 1)
5x5 BandedMatrices.BandedMatrix{Float64}:
 1.0  1.0
 1.0  1.0  1.0
      1.0  1.0  1.0
           1.0  1.0  1.0
                1.0  1.0

julia> a[1, 1:2] = 2
ERROR: BoundsError
 in setindex! at /Users/davide/Software/BandedMatrices.jl/src/BandedMatrices.jl:243
````

The BoundsError is actually taking place at https://github.com/ApproxFun/BandedMatrices.jl/blob/master/src/BandedMatrices.jl#L245.

I can prepare a PR.

### PR DESCRIPTION
**Pull request by gasagna**
Here is a pull request where I have implemented `setindex!`. The merge with upstream was a bit troublesome, so the diff generated by github is not really clear. Looking at the tests is probably a better way to see what was implemented. Please review this and let's discuss if anything needs to be changed.  

There are other methods that I need to implement, but this is the lowest basis.

### CODE REVIEW

**Comment by dlfivefifty** [comment]
Thanks for this!  I'm in the middle of fixing a segfault in *, but will have a look after that.

One comment:  I'm not sure about the A[band(3),:] syntax, since every other case I can think of of A[k,j] has k indicate rows and j indicate columns.  I think it's more consistent to use the single indexing notation, so that we would have the following:

```julia
A[band(3)]          # returns the 3rd band.  
sub(A,band(3))  # returns a view into the 3rd band
A[band(3)] = [1,2]  # sets the entries of the 3rd band
sub(A,band(3))[2] = 5   # sets the second entry of the 3rd band
```

This way `band(k)` is exactly equivalent to a `Range`.  For example, 

```julia
A=brand(5,5,1,2)
A[1:5:end]  # returns diagonal
A[band(0)]  # also returns diagonal
```

**Comment by gasagna** [comment]
I agree with you in that the `A[band(0), :]` is a bit awkward. Initially i though that one could use the second index to do fancy things along a band, but then it is not straightforward or evident what that second index should mean (row index? column index?). I will change it to what you proposed, thanks!

**Comment by dlfivefifty** [comment]
PS I've added you as a collaborator.  We may also want to move BandedMatrices.jl outside of ApproxFun down the line to make it feel more like a stand alone package.

**Comment by gasagna** [comment]
Thanks! If we decide to change name to this package we can do it at the same time when you move it out of ApproxFun. Personally, I also like BandMatrices, because it is shorter. I am not a native speaker though.

**Comment by dlfivefifty** [comment]
Is this ready to merge?  I looked through and I'm happy with the current syntax

**Comment by gasagna** [comment]
Yes, it is ready. You can merge, thanks!

**Comment by gasagna** [comment]
Hi, can this be merged?

**Pull request merged**
